title: "Ahya Muhammad Abiyu Salam"
description: "Data Science & Cloud Engineering Portfolio"
url: "https://username.github.io"
baseurl: "https://412biyubiy.github.io/portofolio/"  # Kosong kalau pake domain khusus, atau "/portfolio" kalau project site

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Collections
collections:
  projects:
    output: true
    permalink: /portfolio/:name/

# Exclude dari build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Front matter defaults
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
